server:
  port: 8001

spring:
  application:
    name: springcloud-service-user

eureka:
  instance:
      #自定义服务名称类型
      instance-id: springcloud-service-user-8001
      #访问路径可以显示IP地址
      prefer-ip-address: true


