server:
  port: 8005

spring:
  application:
    name: springcloud-service-order

eureka:
  instance:
      #自定义服务名称类型
      instance-id: springcloud-service-order-8005
      #访问路径可以显示IP地址
      prefer-ip-address: true



