server:
  port: 8003

spring:
  application:
    name: springcloud-service-restaurant

eureka:
  instance:
      #自定义服务名称类型
      instance-id: springcloud-service-restaurant-8003
      #访问路径可以显示IP地址
      prefer-ip-address: true



