server:
  port: 7001

eureka:
  instance:
    #Eureka服务端的实例名称
    hostname: 127.0.0.1
  client:
    #是否向注册中心注册自己
    register-with-eureka: false
    #是否启用获取服务注册信息,false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址,查询服务和注册服务都需要依赖这个地址，多个以逗号分隔
      #单机
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群
      #defaultZone: http://127.0.0.1:7002/eureka/,http://127.0.0.1:7003/eureka/
  server:
    #留存的服务实例低于多少比例进入保护模式
    renewal-percent-threshold: 0.5
    #是否开启保护模式（默认是true）
    enable-self-preservation: true
