server:
  port: 9001

#Feign-Hystrix
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
      #,http://127.0.0.1:7002/eureka/,http://127.0.0.1:7003/eureka/
  instance:
      instance-id: springcloud-comsumer-client-9001
      prefer-ip-address: true
spring:
  application:
    name: springcloud-comsumer-client

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8
