server:
  port: 3344

spring:
  application:
    name: springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bearcat926/springcloud-config.git
          #git@github.com:bearcat926/springcloud-config.git

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
      #,http://127.0.0.1:7002/eureka/,http://127.0.0.1:7003/eureka/