server:
  port: 8004

spring:
  application:
    name: springcloud-service-menu

eureka:
  instance:
      #自定义服务名称类型
      instance-id: springcloud-service-menu-8004
      #访问路径可以显示IP地址
      prefer-ip-address: true



